Repository googleapis/python-analytics-data, pull requests merged in 2021-03, with the labels that each got.

#17 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: analyticsdata, cla: yes, samples

#44 fix: fix from_service_account_info for async clients
  google/analytics/data_v1alpha/services/alpha_analytics_data/async_client.py
  google/analytics/data_v1beta/services/beta_analytics_data/async_client.py
  noxfile.py
  synth.metadata
  tests/unit/gapic/data_v1alpha/__init__.py
  tests/unit/gapic/data_v1alpha/test_alpha_analytics_data.py
  tests/unit/gapic/data_v1beta/__init__.py
  tests/unit/gapic/data_v1beta/test_beta_analytics_data.py
Labels: api: analyticsdata, cla: yes, context: partial

#46 fix(v1beta): rename the 'page_size', 'page_token', 'total_size' fields to 'limit', 'offset' and 'row_count' respectively
  docs/data_v1beta/beta_analytics_data.rst
  google/analytics/data_v1alpha/types/__init__.py
  google/analytics/data_v1beta/services/beta_analytics_data/async_client.py
  google/analytics/data_v1beta/services/beta_analytics_data/client.py
  google/analytics/data_v1beta/services/beta_analytics_data/pagers.py
  google/analytics/data_v1beta/types/__init__.py
  google/analytics/data_v1beta/types/analytics_data_api.py
  synth.metadata
  tests/unit/gapic/data_v1beta/test_beta_analytics_data.py
Labels: api: analyticsdata, cla: yes, context: full

#48 chore: add pre-commit-config to renovate ignore paths
  renovate.json
  synth.metadata
Labels: api: analyticsdata, cla: yes, context: full

#51 build(python): fail nox sessions if a python version is missing
  noxfile.py
  synth.metadata
Labels: api: analyticsdata, cla: yes, context: full

#54 chore: upgrade gapic-generator-python to 0.43.1
  google/analytics/data_v1alpha/services/alpha_analytics_data/transports/base.py
  google/analytics/data_v1alpha/services/alpha_analytics_data/transports/grpc.py
  google/analytics/data_v1alpha/services/alpha_analytics_data/transports/grpc_asyncio.py
  google/analytics/data_v1beta/services/beta_analytics_data/transports/base.py
  google/analytics/data_v1beta/services/beta_analytics_data/transports/grpc.py
  google/analytics/data_v1beta/services/beta_analytics_data/transports/grpc_asyncio.py
  synth.metadata
Labels: api: analyticsdata, cla: yes, context: full

#55 docs: update region tag names to match the convention
  samples/snippets/quickstart.py
  samples/snippets/quickstart_json_credentials.py
  samples/snippets/quickstart_oauth2.py
Labels: api: analyticsdata, cla: yes
